// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zufxvtdtwwlhmszffjxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Znh2dGR0d3dsaG1zemZmanhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTg1NjUsImV4cCI6MjA2NDk5NDU2NX0.DKHxdUxAgaMXv-A2T9OdigX7W7_JGDbkiFki8D-YWfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);